### ISSUE TITLE
Crashing on RP Pico w/ Touch screen

### ISSUE THREAD

**Issue by JakobSkt** [slint-ui/slint-mcu-rust-template#4]
## Hey! 
Running this project on a RP Pico with the Waveshare Touch Screen simply **results in a white noise image on the screen**. Like that of old tv's with no signal! 
I've followed the entire guide and the simulator runs the template all fine. No errors occur when compiling or uploading.
There are two warnings on main.rs at line 40, but other than that, no issues! The log when compiling is below:

<img width="910" alt="image" src="https://github.com/user-attachments/assets/1a372d06-7045-43c8-8a37-c7774c8e3ddf">

I have managed to get the Printer Demo running on the Pico, so I know that it and the screen works - but I can't figure out why this template isn't working.

**Comment by ogoffart** [comment]
The warning are there because the dependencies haven't been updated in a while.

What do you mean with noisy images on the screen? Do you have pictures?

**Comment by JakobSkt** [comment]
This is the screen I get when compiling the project:
![PXL_20240916_065437384 MP](https://github.com/user-attachments/assets/6443b28f-ae28-41a6-8b8b-c031c563ec4f)

**Comment by ogoffart** [comment]
I could reproduce the problem. Indeed, the template is broken.
Thanks for notigying us.
I did a bisect of Slint and the commit that breaks it is e0efbc49bd11072a05bef3b91db91879b5513231

I guess the problem might be that we don't set the size of the window to the size of the screen.
